apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderservice
  template:
    metadata:
      labels:
        app: orderservice
    spec:
      containers:
        - env:
            - name: DB_SERVER
              value: postgresqldb-order
            - name: POSTGRES_DB
              value: orderservice
            - name: POSTGRES_PASSWORD
              value: "4526357"
            - name: POSTGRES_USER
              value: postgres
          image: mpinchuk/orderservice:latest
          name: orderservice
          ports:
            - containerPort: 8084
