apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: orderservice
  name: orderservice
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: orderservice
  strategy: { }
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: orderservice
    spec:
      containers:
        - env:
            - name: DB_SERVER
              value: postgresqldb-order
            - name: POSTGRES_DB
              value: orderservice
            - name: POSTGRES_PASSWORD
              value: "4526357"
            - name: POSTGRES_USER
              value: postgres
          image: mpinchuk/orderservice:latest
          imagePullPolicy: ""
          name: orderservice
          ports:
            - containerPort: 8084
          resources: { }
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
        - name: postgres-data-order
          persistentVolumeClaim:
            claimName: postgres-data-order
status: { }
