apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresqldb-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresqldb-order
  template:
    metadata:
      labels:
        app: postgresqldb-order
    spec:
      containers:
        - env:
            - name: POSTGRES_DB
              value: orderservice
            - name: POSTGRES_PASSWORD
              value: "4526357"
            - name: POSTGRES_USER
              value: postgres
          image: postgres
          imagePullPolicy: ""
          name: postgresqldb-order
          ports:
            - containerPort: 5432
